### ISSUE TITLE
Performance Improvements through Web Workers: Lack of Firefox support?

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia-web-sdk#220]
Webaverse uses web worker features that are not (currently) available on Firefox. I wonder then, the features that we want to use, will this also have an issue on Firefox and will we have to have diverging pathways to support both platforms? Ideally we would not have to do that. It causes code maintenance issues and overhead, also it will have a degraded experience in comparison to Chromium users.

**Comment by ctrlaltdavid** [comment]
Web Workers are generally well supported, including in Firefox: https://caniuse.com/?search=Web%20Worker
We can make sure that we don't use Chrome-specific features.
