### ISSUE TITLE
SDK package version number should change with feature changes

### ISSUE THREAD

**Issue by Misterblue** [vircadia/vircadia-web-sdk#30]
At the moment, the sdk package version is a constant "0,0,2" in the file "src/Vircadia.ts" and the NPM package version in "package.json" is "0.0.1".

The accessable sdk version should somehow be set from the NPM package version

Additionally, the sdk version should change as features change. Particularly when there are protocol changes or API additions.

**Comment by ctrlaltdavid** [comment]
Currently, the two places to change the version number are:
- package.json
- Vircadia.ts

**Comment by Misterblue** [comment]
The SDK package version is still not being updated. There have been bug repair and feature addition PRs merged but the version number is still 0.0.5. A PR merge should bump the package version number!

**Comment by ctrlaltdavid** [comment]
Version number was set for the 2022.1.0 release and has been incremented to 2022.1.1 for the new development work and the next release.
