### ISSUE TITLE
Firefox mic audio input doesn't work

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia-web-sdk#39]
Firefox mic input doesn't work because it doesn't automatically handle different sampling rates in the Web Audio context that is grabbing the mic audio input and feeding it to the 24kHz Vircadia audio pipeline. Edge/Chromium, on the other hand, automatically do the conversion.

Firefox console error message: `"Uncaught (in promise) DOMException: AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported."`

We need to resample audio ourselves. For example, https://stackoverflow.com/questions/52787510/reducing-sample-rate-of-a-web-audio-spectrum-analyzer-using-mic-input

Probably best to implement as a new `AudioWorkletProcessor` alongside the existing AudioInputProcessor.ts, and insert it into the audio chain in `AudioInput.#setUpAudioContext()` - and perhaps insert only if Firefox or that error message is encountered.

**Comment by namark** [comment]
Well, hit another brick wall with my idea of using OfflineAudioContext, as it's not available to audio worklets. In fact most of everything is not available as they run in a different context. I don't want to throw it all away yet, so will try to move the processing out of the worklet. If that doesn't work out either I guess will have to use one of the hand rolled resampling algorithms.
