### ISSUE TITLE
Implement Basic Entity Server Support

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia-web-sdk#49]
- [x] Add `EntityServer` class that connects to the domain server.
	- Basic `EntityServer.ts` class.
	- Unit test, "Can create an EntityServer with a DomainServer".
	- Integration test, "States when connect to and disconnect from a domain".
	- Update `Vircadia.ts` and associated integration test.
	- Add EntityServer section to example app, with connection status.
	- PR: https://github.com/vircadia/vircadia-web-sdk/pull/93

- [x] Request entity data from the entity server.
	- Add a `PacketScribe.EntityQuery.write()` method and unit test.
	- Update `PacketType` documentation.
	- Add an `EntityServer.update()` method based on the part of `Application::update()` which calls `queryOctree()`. Implement `_queryExpiry` but leave `viewIsDifferentEnough` for now.
	- Add an `EntityServer.#queryOctree()` method based on `Application::queryOctree()` with which sends `EntityQuery` packets to entity server.
	  Include a `#_physicsEnabled` member hard-coded to `true`, and implement the `if(isModifiedQuery)` that uses it but log an error in the "if" branch; implement just the "else" branch.
	  The `#_conicalViews` member value should be hard-coded for now (with a "TODO"). Use, say, a sphere at 0,0,0 with radius of 10.0m - e.g., in order to initially obtain just entities near the origin. (The `#_conicalViews` member value will need to be shared with the `AvatarMixer` via a "cameras" object or similar later on.)
	  The `lodManager` values should be hard-coded for now (with a "TODO").
	- Implement `OctreeQuery` just enough to satisfy the needs of the above.
	- Confirm receipt at entity server through instrumentation.
	- PR: https://github.com/vircadia/vircadia-web-sdk/pull/98

- [x] Receive packets from the entity server.
	- Add an empty `OctreePacketProcessor` class in `/src/domain/octree`.
	- Add a `EntityServer.#_octreeProcessor` member which  is an `OctreePacketProcessor`.
	- Add a stub of `OctreePacketProcessor.processPacket()` and wire it up per `OctreePacketProcessor::OctreePacketProcessor()` so that it is called when anay entity server-related packet (message) is received. Included a comment that `processPacket()` is being called directly rather than being queued by a call to a `handleOctreePacket()` method.
	- Make `OctreePacketProcessor.processPacket()` log information on packets received but not handled (i.e., all packets at present), along the lines of `AudioClient.#processStreamStatsPacket()`. This will confirm that it is working and remind us of missing code.
	- PR: https://github.com/vircadia/vircadia-web-sdk/pull/105

- [x] Implement `OctreePacketProcessor.processPacket()` for `EntityData` packets.
	- If an `OctreeStats` packet log that the packet was received but not handled and bail early because we're not interested in that packet yet or the voxel data it may contain.
	- Ignore other C++ code except for the `switch` statement. Include a `case` for `EntityData` but for other packets log that they were received but not handled.
	- Make the `EntityData` case call `PacketScribe.EntityData.read()`.
	- Add a `PacketScribe.EntityData.read()` method stub.
	- Add a stub `EntityServer.entityData` signal called after the packet is read.
	- PR: https://github.com/vircadia/vircadia-web-sdk/pull/106

- [x] Implement a `PacketScribe.EntityData.read()` method and make it handle just "Model" entity data for now (i.e., skip over other entity data).
	- A single "Model" entity as the sole entity in a domain. With a unit test.
	- Two or more "Model" entities in a domain. With a unit test.
	- A "Model" entity and other entity types in the domain. (Just the "Model" entity's data should be used.) With a unit test.
	- Editing a single "Model" entity as the sole entity in a domain. With a unit test.
	- List handled entities in a table in the example app (perhaps entity ID, entity type, entity position).
	- PR: https://github.com/vircadia/vircadia-web-sdk/pull/108

	The packet reading starts at `OctreeProcessor::processDatagram()` then gets rather complex.
	Note the "TO DO"s in _ENTITY SERVER.md_ regarding signals to emit and the possible need for the entity server to maintain a copy of the entity data. The answers will depend on what the `EntityData` packet contains.

... Further work to plan ... See separate comment, below.

**Comment by ctrlaltdavid** [comment]
- [ ] ... Further work to plan:
	- Handle EntityQueryInitialResultsComplete packet.
	- Handle EntityErase packet.
	- Send OctreeDataNack packets.
	- Add `EntitiesMixer` properties or methods to set the view frustum(s) to use in `#queryOctree()`.
	- Support further entity types.
	- A "cameras" object that is shared with `AvatarMixer` that implements `Application::_conicalViews` and is used in `Application::update()`.
	- "To do later" work in design doc.
