### ISSUE TITLE
SIgnalEmitter should return "slot code" so disconnect can match proper connect

### ISSUE THREAD

**Issue by Misterblue** [vircadia/vircadia-web-sdk#62]
When connecting a slot to the SignalEmitter, the disconnect just takes the slot again which is a handle to the original function. I have a class that makes connections for several different requestors so there would be multiple slots with the same signature (presuming the JS context doesn't make the signatures different).

It would be "cleaner" if SignalEmitter.connect returned a code (number?) for the connect that would be used to do the SignalEmitter.disconnect.

```
const subscriptionCode = signaler.connect(handleEvent);
...
signaler.disconnect(subscriptionCode);
```

**Comment by ctrlaltdavid** [comment]
`Signal.connect(slot)` and `Signal.disconnect(slot)` connect/disconnect a specific `slot` function object, not a function signature.

The pseudo-code should be able to be recast as:
```
const subscriptionCode = handleEvent;
signaler.connect(subscriptionCode);  // Or signaler.connect(handleEvent); 
...
signaler.disconnect(subscriptionCode);
```

**Comment by Misterblue** [comment]
I have figured out how to make this work.
